services:
  angular_app:
    container_name: angular_app
    build:
      context: ./reservasFront
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - java_app
    

  java_app:
    container_name: java_app
    ##image: pee-java-app:1.0.0
    build:
      context: ./daw
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: java_db
    volumes:
      - ./:/app
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/data


